### ISSUE TITLE
Kibana -- Connection Failed

### ISSUE THREAD

**Issue by NicoYUE** [immunochomik/kibana3#2]
Hello,

I'm trying this version of Kibana so I can run it with ELS 2.3.

This solution worked for like 1 or 2 days but after that, it seems like Kibana won't reach ELS anymore.
Of course I added cors on all of my ELS instances and I have no memory usage issues either.

No idea where I should look into for this. At first I was thinking about a NGINX conf problem but if I point Kibana to an actual ELS 1.7 cluster, I have no problem at all.

thanks in advance

**Comment by LikeARock47** [comment]
I have a similar issue.  Trying to run this with Elasticsearch 2.3 together on the same box.  I also have set the following in the ELS config:  
`network.bind_host: ["_local_", "_site_"]`
`network.publish_host: _site_`
`#`
`http.port: 9200`
`#`
`http.cors.enabled: true`
`http.cors.allow-origin: "/.*/"`

I can hit the Kibana 3 start page, but whenever I try to load a dashboard or create one it throws up the "connection failed" page.

Kibana 4 is working fine with the ELS instance on this box.

**Comment by elwarren** [comment]
Came here to say the same thing.  Appears that CORs is broken in 2.3 and is fixed in 2.3.2 but I haven't tested it yet.

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-2.3.html#_cors_support_broken_in_2_3_0_and_2_3_1

**Comment by LikeARock47** [comment]
Good find.  But I updated Elasticsearch to 2.3.2 and still not working.

**Comment by elwarren** [comment]
Strange. I upgraded to 2.3.2 and it works for me after clearing browser cache.

**Comment by immunochomik** [comment]
Well I have not tried it with 2.3, I will when I will have some time and then I will get back to you

**Comment by immunochomik** [comment]
I have tried it with es 2.3.0 and in fact it does not work, this is a cors issue as browser does not want to show the content of the response to a request due to mussing headers. It can not be fixed in kibana it self. But fortunately the problem vanishes in Elasticsearch 2.3.2 (according to @elwarren). I have tried 2.3.5 and it is fixed there
